### ISSUE TITLE
Parse DOM of mail.google.com email for Subject, body, and sender email

### ISSUE THREAD

**Issue by cms-WebDesign** [amills93/No-Phishing-Zone#19]
We will need to devise a way to parse the DOM of an email in order to easily identify:

- [ ] Subject
- [ ] Body
- [ ] Sender Email

**Comment by amills93** [comment]
Parsing the web syntax appearing to be more difficult than first envisioned.

**Comment by cms-WebDesign** [comment]
Closing and re-opening new issue per what we learned today 3/2/22
