### ISSUE TITLE
Verify that the div class <nh aHU> is used across sessions to identify email bodies

### ISSUE THREAD

**Issue by cms-WebDesign** [amills93/No-Phishing-Zone#22]
In the 3/02/22 meeting we saw that the email header was labeled as <div class="nH aHU">. We verified this was accurate for several emails in Chris inbox we need to check this is persistent across different browsers and sessions.

- [ ] Adam
- [ ] Dennis
- [x] Dylan

**Comment by cms-WebDesign** [comment]
I have checked several of my emails across multiple sessions and it seems the body of the email is in that single tag need other members to verify the same.

**Comment by BigElkHunter** [comment]
I checked a gmail email of mine and found the tag in the body of the email.
