### ISSUE TITLE
Milestone 3 Presentation

### ISSUE THREAD

**Issue by amills93** [amills93/No-Phishing-Zone#40]
The video may be watched by external guests - so please address an audience beyond just the instructor. Videos should be no longer than 30 minutes.

Your presentation should cover:

High level goals, initial scope, and adjustment to scope (keep it succinct)
Project methodology followed over the project
Principle Project findings and outcomes
Demos of any relevant tooling / code / attacks / etc that resulted from the work and/or findings

**Comment by cms-WebDesign** [comment]
https://docs.google.com/presentation/d/1urUjiFybTK6csuzwGSLImW9U47sdx3-mQCSHQvQ1Btw/edit?usp=sharing

Started working on the Presentation have most of it wrapped up

**Comment by amills93** [comment]
Draft was  posted and then reviewed.  Presentation recording set for next week.
