### ISSUE TITLE
Final Report: Packaging and Release [Last]

### ISSUE THREAD

**Issue by amills93** [amills93/No-Phishing-Zone#43]
This goes into finalreport.md within the Milestone 3 folder.  Essentially, it will be a compilation  of previous work with minor updates to modernize it. 

Note: Cannot be done until extension is complete. We will use GitHub to version this release.

**Comment by cms-WebDesign** [comment]
Questions for Professor:
Do we package the entire repo or just the folder with the extension? 
If just the folder with the extension does it need a brief readme for installation instructions?
Any other things involved with the packing or the extension or from a development side? (I added a license anything else)
